### PR TITLE
Cmake convertion for Anypia32

### PR DESCRIPTION
**Pull request by thadk**
The SSA's calculator on Windows uses Visual Studio 2015 `MSBuild.exe` which several sources noted is not compatible with `emscripten` and `emcc`. This pull request used the cmake-converter (see [readme](https://github.com/codeforboston/anypia-js/tree/ad699e3aff3f6e6b728d81afc853c3e2fcfcba22)) and allows a somewhat successful win32 build along the lines of the MSBuild.exe one.

[Example command prompt output from cmake build](https://gist.github.com/thadk/29dc65aa37ca10f13b268e25b9b55cdd)

I believe underneath, CMake is running Microsoft's NMake instead of MSBuild, so we can begin to ignore the `emcc` incompatible solution files and focus on a workable process for the libraries that we'd need for the javascript frontend.

That said, the anypia32.exe executable from CMake/Nmake doesn't work as well as the one that `MSBuild.exe` generates on the same environment. There are no build errors but something may yet be missing. Welcome to offer any suggestions on what this immediate error on running it might mean:
image

We really only need the libraries from `oactobjs32` projects in javascript so this might only be a small problem, not sure.

### CODE REVIEW

**Comment by thadk** [comment]
We noticed that `anypiab` does successfully build and run with this process. 

`anypiab` is a very simple app that expects a series of filenames to open on stdin and then writes an `output` file.

Maybe we can go ahead next and convert that `anypiab\CMakeList.txt` to build with emscripten/`encc`. The win32 GUI isn't so essential as long as the command line one and its libraries are built robustly enough.

**Comment by mrpippy** [comment]
Sorry, I haven't worked on this in a week or two.
When I left off, I was working on building the oactobjs32 libraries and anypiab on macOS using Meson, the libraries were actually building with almost no problems.
I first tried using the `oactobjs/linux` directory for includes but that just caused problems, building against the `oactobjs/windows` includes actually worked much better. I doubt the Linux files have been tested in years, and aside from maybe the PathnameSeparator, the other differences seem to be making up for some C++ library features that were apparently missing/not working on Linux long ago.

There's a lot to like about Meson but it's very restrictive about how you can structure a project (all subprojects have to go in a certain directory), CMake is more flexible and I think it's the right way to go here.

I agree that there isn't really a need to build the Win32 app using a different build system, I think it's enough to just keep it building with the original/upstream toolchain and project files for verification.

If it's ok with you, I think I'd prefer to make the CMakeLists files from scratch rather than converting them, there's a lot of leftover stuff from the MSVC projects that isn't needed. I made some good progress tonight, hopefully I'll have something working in the next day or two.

**Comment by thadk** [comment]
@mrpippy Thanks, that sounds good: I see that `.\b2 toolset=emscripten` for boost may be broken on Windows, so could be essential to use mac in the end, if emscripten's `SET_BOOST_HEADERS=1` that I used is insufficient. Take a look at my other PR. Maybe it'll help you somehow. I should take a break for a few days, hah. 

I was starting from 0 knowledge of CMake so I had to get the converter boilerplate to figure anything out. Welcome to strip it down, switch it out for Meson, or do it in a more natural way. It is already pretty annoying to manage the four files and repetition between them.

I put much of my process in the latest readme but I think it should be possible to get #3 running to the point I did with Travis-CI. Maybe that would be a good next task for me.

-Thad

**Comment by thadk** [comment]
We don't need anypia32 for now, closing.

**Pull request closed without merging**
